apiVersion: apps/v1
kind: Deployment
metadata:
  name: better
spec:
  replicas: 2
  selector:
    matchLabels:
      app: better
  template:
    metadata:
      labels:
        app: better
    spec:
      containers:
        - name: better
          image: registry.digitalocean.com/cloud-ide-registry/better:${IMAGE_TAG}
          env:
            - name: DD_AGENT_HOST
              value: "datadog-agent"
            - name: DD_ENV
              value: "staging"
            - name: DD_SERVICE
              value: "better-node-app"
            - name: DD_TRACE_DEBUG
              value: "true"
          ports:
            - containerPort: 8080